[package]
name = "git-remote-icp"
description = "A Git remote helper for the Internet Computer"
version = "0.1.0"
edition = "2021"
authors = ["Paul Young <84700+paulyoung@users.noreply.github.com>"]

[[bin]]
name = "git-remote-icp"

[dependencies]
anyhow = "1.0"
clap = { version = "3.2", features = ["derive"] }
env_logger = "0.9"
git-features = { git = "https://github.com/Byron/gitoxide", rev="0c9c48b3b91a1396eb1796f288a2cb10380d1f14" }
git-protocol = { git = "https://github.com/Byron/gitoxide", rev="0c9c48b3b91a1396eb1796f288a2cb10380d1f14", features = ["async-client"] }
git-repository = { git = "https://github.com/Byron/gitoxide", rev="0c9c48b3b91a1396eb1796f288a2cb10380d1f14", features = ["async-network-client-async-std"] }
git-transport = { git = "https://github.com/Byron/gitoxide", rev="0c9c48b3b91a1396eb1796f288a2cb10380d1f14", features = ["async-client"] }
log = "0.4"
strum = { version = "0.24", features = ["derive"] }
tokio = { version = "1.12", features = ["full"] }
