[package]
name = "git-remote-icp"
description = "A Git remote helper for the Internet Computer Protocol"
version = "0.1.0"
edition = "2021"
authors = ["Paul Young <84700+paulyoung@users.noreply.github.com>"]

[[bin]]
name = "git-remote-icp"

[dependencies]
anyhow = "1.0"
bstr = "1.0"
clap = { version = "3.2", features = ["derive"] }
env_logger = "0.9"
git-features = { git = "https://github.com/Byron/gitoxide", rev="409b769f088854670176ada93af4f0a1cebed3c5" }
git-hash = { git = "https://github.com/Byron/gitoxide", rev="409b769f088854670176ada93af4f0a1cebed3c5" }
git-odb = { git = "https://github.com/Byron/gitoxide", rev="409b769f088854670176ada93af4f0a1cebed3c5" }
git-pack = { git = "https://github.com/Byron/gitoxide", rev="409b769f088854670176ada93af4f0a1cebed3c5" }
git-packetline = { git = "https://github.com/Byron/gitoxide", rev="409b769f088854670176ada93af4f0a1cebed3c5" }
git-protocol = { git = "https://github.com/Byron/gitoxide", rev="409b769f088854670176ada93af4f0a1cebed3c5", features = ["async-client"] }
git-refspec = { git = "https://github.com/Byron/gitoxide", rev="409b769f088854670176ada93af4f0a1cebed3c5" }
# TODO: remove or feature gate async-std
git-repository = { git = "https://github.com/Byron/gitoxide", rev="409b769f088854670176ada93af4f0a1cebed3c5", features = ["async-network-client-async-std"] }
git-transport = { git = "https://github.com/Byron/gitoxide", rev="409b769f088854670176ada93af4f0a1cebed3c5", features = ["async-client"] }
git-traverse = { git = "https://github.com/Byron/gitoxide", rev="409b769f088854670176ada93af4f0a1cebed3c5" }
log = "0.4"
strum = { version = "0.24", features = ["derive"] }
tokio = { version = "1.12", features = ["full"] }
