[package]
name = "git-remote-ic"
description = "A Git remote helper for the Internet Computer"
version = "0.1.0"
edition = "2021"
authors = ["Paul Young <84700+paulyoung@users.noreply.github.com>"]

[[bin]]
name = "git-remote-ic"

[dependencies]
clap = { version = "3.2", features = ["derive"] }
env_logger = "0.9"
git-protocol = { version = "0.20", features = ["blocking-client"] }
# git-transport = { version = "0.20", features = ["blocking-client"] }
git-transport = { version = "0.20", features = ["http-client-curl"] }
log = "0.4"
# picky = "6.3"
tokio = { version = "1.12", features = ["full"] }
