[package]
name = "git-remote-ic"
description = "A Git remote helper for the Internet Computer"
version = "0.1.0"
edition = "2021"
authors = ["Paul Young <84700+paulyoung@users.noreply.github.com>"]

[[bin]]
name = "git-remote-ic"

[dependencies]
anyhow = "1.0"
bstr = "1.0"
clap = { version = "3.2", features = ["derive"] }
env_logger = "0.9"
gitoxide-core = { path = "../../../../../Byron/gitoxide/paulyoung/git-transport/gitoxide-core", features = ["blocking-client"] }
git-features = { path = "../../../../../Byron/gitoxide/paulyoung/git-transport/git-features" }
git-hash = { path = "../../../../../Byron/gitoxide/paulyoung/git-transport/git-hash" }
git-protocol = { path = "../../../../../Byron/gitoxide/paulyoung/git-transport/git-protocol", features = ["blocking-client"] }
git-transport = { path = "../../../../../Byron/gitoxide/paulyoung/git-transport/git-transport", features = ["http-client-curl"] }
log = "0.4"
strum = { version = "0.24", features = ["derive"] }
tokio = { version = "1.12", features = ["full"] }
