[package]
name = "git-remote-ic"
description = "A Git remote helper for the Internet Computer"
version = "0.1.0"
edition = "2021"
authors = ["Paul Young <84700+paulyoung@users.noreply.github.com>"]

[[bin]]
name = "git-remote-ic"

[dependencies]
clap = { version = "3.2", features = ["derive"] }
env_logger = "0.9"
git-features = { path = "../../../../../Byron/gitoxide/paulyoung/git-transport/git-features" }
# git-protocol = { version = "0.20", features = ["blocking-client"] }
git-protocol = { path = "../../../../../Byron/gitoxide/paulyoung/git-transport/git-protocol", features = ["blocking-client"] }
# git-transport = { version = "0.20", features = ["blocking-client"] }
# git-transport = { version = "0.20", features = ["http-client-curl"] }
git-transport = { path = "../../../../../Byron/gitoxide/paulyoung/git-transport/git-transport", features = ["http-client"] }
log = "0.4"
reqwest = { version = "0.11", features = ["default-tls", "blocking"] }
strum = { version = "0.24", features = ["derive"] }
tokio = { version = "1.12", features = ["full"] }
